package com.medico.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "ai_analysis_results")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AIAnalysisResult {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "patient_id", nullable = false)
    private Patient patient;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "vital_reading_id")
    private VitalReading vitalReading;

    // Stored as JSON string: ["condition1", "condition2"]
    @Column(columnDefinition = "TEXT")
    private String possibleConditions;

    @Column(nullable = false)
    private String severity;

    @Column(columnDefinition = "TEXT")
    private String recommendation;

    @Column(nullable = false, length = 500)
    private String disclaimer = "⚠️ AI-Assisted Clinical Insight: This analysis is generated by AI and should NOT be used as a final diagnosis. Always apply clinical judgment.";

    @Column(nullable = false)
    private LocalDateTime analyzedAt;

    @PrePersist
    protected void onCreate() {
        analyzedAt = LocalDateTime.now();
    }
}
